"""create projects table

Revision ID: ad22a7a7f284
Revises: 617b47179bb1
Create Date: 2026-07-13 18:54:50.244523
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ad22a7a7f284"
down_revision: str | None = "617b47179bb1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "("
            "(status = 'active' AND archived_at IS NULL)"
            " OR "
            "(status = 'archived' AND archived_at IS NOT NULL)"
            ")",
            name="ck_projects_archive_consistency",
        ),
        sa.CheckConstraint("btrim(name) <> ''", name="ck_projects_name_not_blank"),
        sa.CheckConstraint("btrim(slug) <> ''", name="ck_projects_slug_not_blank"),
        sa.CheckConstraint("status IN ('active', 'archived')", name="ck_projects_status"),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "slug", name="uq_projects_workspace_slug"),
    )
    op.create_index(
        "ix_projects_created_by_user_id", "projects", ["created_by_user_id"], unique=False
    )
    op.create_index("ix_projects_workspace_id", "projects", ["workspace_id"], unique=False)
    op.create_index(
        "ix_projects_workspace_status", "projects", ["workspace_id", "status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_projects_workspace_status", table_name="projects")
    op.drop_index("ix_projects_workspace_id", table_name="projects")
    op.drop_index("ix_projects_created_by_user_id", table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
